- name: Install dependencies for Autoware build
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
    update_cache: true

- include_role:
    name: bouncmpe.autoware.get_build_deps_rmw_implementation

- include_role:
    name: bouncmpe.autoware.get_build_deps_pacmod

- include_role:
    name: bouncmpe.autoware.get_cuda
    when: {{ install_cuda }}