- name: Install dependencies for setting up apt source
  become: true
  ansible.builtin.apt:
    name:
      - python3-vcstool
    update_cache: true

- name: autowarefoundation/autoware
  ansible.builtin.git:
    repo: https://github.com/autowarefoundation/autoware.git
    dest: "{{ autoware_dir }}"
    version: main
    depth: 1
    single_branch: true

- name: Create Autoware source directory if it does not exist
  ansible.builtin.file:
    path: "{{ autoware_src }}"
    state: directory
    mode: '0755'

- name: vcs import autoware repos
  ansible.builtin.shell: vcs import {{ autoware_src }} < "{{ autoware_dir }}/autoware.repos"
  args:
    executable: /bin/bash
    chdir: "{{ autoware_dir }}"

- name: vcs import simulator repos
  ansible.builtin.shell: vcs import {{ autoware_src }} < "{{ autoware_dir }}/simulator.repos"
  args:
    chdir: "{{ autoware_dir }}"
  when: "{{ include_simulator_repos }}"
