# ansible playbook
#
# See: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
# Use: ansible-playbook repos.yml

- hosts: localhost
  connection: local
  vars:
    - ros_distro: galactic
    - ros_distro_type: ros-base
    - autoware_version: main
    - autoware_ws: /tmp/autoware
    - autoware_src: "{{ autoware_ws }}/src"
    - autoware_install_dir: "/opt/autoware/{{ ros_distro }}"

  roles:
    - role: bouncmpe.autoware.ros2
    - role: bouncmpe.autoware.get_autoware_build_deps
    - role: bouncmpe.autoware.autoware_core_repos
    - role: bouncmpe.autoware.autoware_universe_repos
    - role: bouncmpe.autoware.get_autoware_deps_rosdep
    - role: bouncmpe.autoware.build_autoware_colcon

