# ansible playbook
#
# See: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
# Use: ansible-playbook repos.yml

- hosts: localhost
  connection: local
  vars:
    - autoware_dir: /tmp/autoware
    - autoware_src: "{{ autoware_dir }}/src"
    - autoware_install: "/opt/autoware/{{ rosdistro }}"
    - rosdistro: galactic
    - installation_type: ros-base

  roles:
    - role: bouncmpe.autoware.ros2
    - role: bouncmpe.autoware.autoware_core_repos
    - role: bouncmpe.autoware.autoware_universe_repos
    - role: bouncmpe.autoware.autoware_build_deps
    - role: bouncmpe.autoware.autoware_rosdep
    - role: bouncmpe.autoware.autoware_colcon_build