- name: Install dependencies for setting up apt source
  become: true
  ansible.builtin.apt:
    name:
      - python3-rosdep 
    update_cache: true

- name: Run 'sudo rosdep init'
  become: true
  ansible.builtin.command:
    cmd: rosdep init
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
   
- name: rosdep update
  ansible.builtin.shell: rosdep update
  args:
    executable: /bin/bash
    chdir: "{{ autoware_dir }}"

- name: rosdep install
  ansible.builtin.shell: >-
    source /opt/ros/{{ rosdistro }}/setup.bash && 
    DEBIAN_FRONTEND=noninteractive rosdep install -y --ignore-src --from-paths src --rosdistro {{ rosdistro }} 
  args:
    executable: /bin/bash
    chdir: "{{ autoware_dir }}"
